services:
  restorator.api:
    container_name: restorator.server
    image: ${DOCKER_REGISTRY-}restoratorapi
    build:
      context: .
      dockerfile: Restorator.API/Dockerfile
    depends_on:
    - db
    environment:
      ConnectionStrings__LocalConnection: "Server=db;Database=restorator;User Id=sa;Password=Qwerty123;TrustServerCertificate=true;Trusted_connection=false"

  db:
    container_name: restorator.db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Qwerty123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db-data:/var/opt/mssql/data  
    ports:
      - "8612:1433"